import os
import pandas as pd

# Path to the CSV generated by your scraper
FILE = "cache/tullys_menu.csv"

def test_should_pass():
    print("\nAlways True!")
    assert True

def test_tullyscraper_menu_csv_file_exists():
    print(f"Expect {FILE} to exist!")
    assert os.path.exists(FILE)

def test_tullyscraper_menu_csv_file_proper_rows_and_cols():
    df = pd.read_csv(FILE)
    print(f"Found {df.shape[0]} rows and {df.shape[1]} columns")

    # Ensure there are 4 columns: category, name, price, description
    assert df.shape[1] == 4

    # Accept flexible number of rows as long as it's reasonable
    assert df.shape[0] >= 100


# Optional: allows running directly for debugging
if __name__ == "__main__":
    test_should_pass()
    test_tullyscraper_menu_csv_file_exists()
    test_tullyscraper_menu_csv_file_proper_rows_and_cols()
